name: Builds

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Create artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Chrome
      run: |
        mkdir -p chrome
        cp -R -t chrome *.{js,json,png,jpg,html,css} LICENSE
        rm -f chrome/Chrome.png

    - uses: actions/upload-artifact@v4
      with:
        name: chrome
        path: chrome
